// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    acompanhamento: {
        name: "acompanhamento";
        parameters: Record<string, never>;
        result: Array<{
          /** Nome do vendedor responsável pela carteira do cliente (silver.vendedores.nome). Só vendedor ativo com carteira vigente entra na fila. */
          vendedor: string;
          /** @sqlType BIGINT */
          na_fila: number;
          /** @sqlType BIGINT */
          trabalhados: number;
          /** @sqlType BIGINT */
          vendeu: number;
          /** @sqlType BIGINT */
          vai_pensar: number;
          /** @sqlType BIGINT */
          sem_interesse: number;
          /** @sqlType BIGINT */
          nao_atendeu: number;
        }>;
      };
    fila: {
        name: "fila";
        parameters: {
          /** STRING - use sql.string() */
          vendedor: SQLStringMarker;
        };
        result: Array<{
          /** Nome do vendedor responsável pela carteira do cliente (silver.vendedores.nome). Só vendedor ativo com carteira vigente entra na fila. */
          vendedor: string;
          /** Posição do cliente na fila deste vendedor — 1 é o próximo a ligar. Calculada por ROW_NUMBER() sobre os 200 clientes de maior score, particionado por vendedor. */
          ordem: number;
          /** Identificador do cliente. Liga com gold.dim_cliente e gold.score_propensao. */
          cliente_id: number;
          /** Nome do cliente. */
          razao_social: string;
          /** Cidade do cliente. */
          cidade: string;
          /** UF do cliente. */
          uf: string;
          /** Probabilidade de compra nos próximos 7 dias (gold.score_propensao.score). Está entre os 200 maiores scores da base elegível. */
          score: number;
          /** Quartil do score entre todos os 3.000 clientes pontuados: Fria, Morna, Quente, Muito quente. */
          faixa: string;
          /** Ticket médio histórico do cliente (gold.features_cliente.ticket_medio) — quanto ele costuma gastar por pedido. */
          ticket_medio: number;
          /** Frase em português explicando por que ligar para este cliente agora: oportunidade aberta, atraso no ritmo, ausência de pedido recente, lançamento comprado ou visita sem conversão. Nunca nula — sem sinal específico, cai no motivo genérico de score alto. */
          motivo: string;
          /** SKU da marca preferida do cliente (por receita histórica) já comprado por ele mas sem compra nos últimos 90 dias, com o saldo do snapshot mais recente de silver.estoque. Frase genérica quando não há SKU elegível. */
          sugestao: string;
          /** Desfecho da ligação. Um de: vendeu | vai_pensar | sem_interesse | nao_atendeu. */
          retorno_status: string;
          /** Texto livre do vendedor sobre a conversa — objeção, próximo passo, contexto. Pode ser nulo. */
          retorno_comentario: string;
        }>;
      };
    kpis_semana: {
        name: "kpis_semana";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          contatos: number;
          /** @sqlType BIGINT */
          vendedores: number;
          /** @sqlType DOUBLE */
          receita_esperada: number;
          /** @sqlType DATE */
          referencia: string;
          /** Quantos dos 200 clientes de maior score (out-of-fold) compraram na janela de 7 dias. */
          acertos_top200: number;
          /** Taxa de compra dos 200 clientes de maior score (out-of-fold) dividida pela taxa base — quantas vezes o modelo é melhor que ligar às cegas. */
          lift_top200: number;
          /** Fração de clientes de gold.features_treino que compraram na janela de 7 dias — a taxa de acerto de uma fila sorteada. */
          taxa_base: number;
          /** Versão do modelo no Unity Catalog (lakehouse_rotaperfume.gold.propensao_compra) que gerou esta linha. */
          versao: number;
          /** @sqlType BIGINT */
          ligacoes_registradas: number;
          /** @sqlType BIGINT */
          vendas: number;
        }>;
      };
    vendedores: {
        name: "vendedores";
        parameters: Record<string, never>;
        result: Array<{
          /** Nome do vendedor responsável pela carteira do cliente (silver.vendedores.nome). Só vendedor ativo com carteira vigente entra na fila. */
          vendedor: string;
          /** @sqlType BIGINT */
          contatos: number;
        }>;
      };
  }
}
